import type { MetadataRoute } from "next";

export default function manifest(): MetadataRoute.Manifest {
  return {
    name: "Nguyen Huu Tan — Portfolio",
    short_name: "NguyenHuuTan",
    description: "Portfolio của Nguyen Huu Tan (Tronie Nguyen) — Frontend Developer 6+ năm kinh nghiệm React.js/Next.js.",
    start_url: "/",
    display: "standalone",
    background_color: "#0a0a0f",
    theme_color: "#7c3aed",
    // `/icon` is the 512x512 PNG generated by `src/app/icon.tsx`. Installability checks
    // require both a >=192 and a >=512 icon, plus a maskable variant.
    icons: [
      {
        src: "/icon",
        sizes: "512x512",
        type: "image/png",
        purpose: "any",
      },
      {
        src: "/icon",
        sizes: "512x512",
        type: "image/png",
        purpose: "maskable",
      },
    ],
  };
}
